# Generated by Django 6.1 on 2026-08-20 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='workinghours',
            name='wh_end_after_start',
        ),
    ]
